future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: academicpages
url: https://academicpages.github.io/group-meeting 
name: Your Group Name
description: An initial blog and site for your group meeting
twitter: yourtwitterhandle
calendar: https://yourcalendarurl
mailinglist: https://yourmailinglisturl
gravatar_url: 
disqus_username:
